name: PublishHomepage

on: [push]

jobs:
        deploy:
                name: Deploy Homepage
                runs-on: [self-hosted, linux]
                steps:
                - name: Checkout
                  uses: actions/checkout@v3
                  with:
                          repository: 'hardillb/homepage'
                          path: 'homepage'
                - run: bash ./homepage/scripts/deploy.sh
